/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import koneksi.DBConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class FormMasterPekerjaan extends javax.swing.JInternalFrame {
//declarasi class yang dibutuhkan disini

    DefaultTableModel tableModel;

    /**
     * Creates new form FormMasterPekerjaan
     */
    public FormMasterPekerjaan() {
        initComponents();
        //disini juga, jika form baru berjalan maka semua method disini akan dijalankan
        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pekerjaan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_keluar = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 255));
        setTitle("Data Jabatan Pegawai");

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 102));

        tabel_pekerjaan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_pekerjaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_pekerjaanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pekerjaan);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_tambah)
                    .addComponent(btn_ubah)
                    .addComponent(btn_hapus)
                    .addComponent(btn_batal)
                    .addComponent(btn_keluar))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Karyawan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("No");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama Jabatan:");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(txt_nama))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().equals("") || txt_nama.getText().equals("")) {
            JOptionPane.showMessageDialog(FormMasterPekerjaan.this, "Data Masih Kosong!!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            //disini kita panggil method Simpan data
            input_data();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // sama seperti diatas kita buat if untuk mendeteksi apakah komponent text kosong atau tidak.
        if (txt_id.getText().equals("") || 
                txt_nama.getText().equals("")) {
            JOptionPane.showMessageDialog(FormMasterPekerjaan.this, "Data Masih Kosong!!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            //disini kita panggil method Update data
            update_data();
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if (txt_id.getText().equals("") || txt_nama.getText().equals("")) {
            JOptionPane.showMessageDialog(FormMasterPekerjaan.this, "Data Masih Kosong!!!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            //disini kita panggil method Hapus data
            hapus_data();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // Batal akan menghapus field yang diisikan dalam komponen teks
        txt_id.setText("");
        txt_nama.setText("");
        
        txt_id.requestFocusInWindow();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // Exit akan menghiden atau mematikan form
        //cukup simple yaitu dengan dispose();
        dispose();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void tabel_pekerjaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_pekerjaanMouseClicked
        // kita panggil method disini
        klik_tabel();
    }//GEN-LAST:event_tabel_pekerjaanMouseClicked

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_pekerjaan;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables
private void input_data() {
        //panggil method koneksi
        java.sql.Connection conn = new DBConnection().connect();

        try {
            String sql = "insert into pekerjaan(no ,nm_pekerjaan) values(?,?)";
            java.sql.PreparedStatement stmt = conn.prepareStatement(sql);

            stmt.setString(1, txt_id.getText());
            stmt.setString(2, txt_nama.getText());

            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil disimpan");
            //setelah selesai disimpan maka text akan ksong kembali
            txt_id.setText("");
            txt_nama.setText("");
            //panggil method tampil disini
            tampil_data();

            stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormMasterPekerjaan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void tampil_data() {
        Object[] baris = {"No", "Nama Jabatan"};
        tableModel = new DefaultTableModel(null, baris);
        tabel_pekerjaan.setModel(tableModel);

        //panggil method koneksi
        java.sql.Connection conn = new DBConnection().connect();

        //listing untuk menampilkan data kedalam tabel
        String sql = "Select * From pekerjaan order by no asc";
        java.sql.Statement stmt;
        try {// block try berguna untuk menangkap apabila terjadi kesalahann sehingga tidak terjadi debug seperti VB
            stmt = conn.createStatement();
            java.sql.ResultSet rslt = stmt.executeQuery(sql);
            while (rslt.next()) {
                String id = rslt.getString("no");
                String pekerjaan = rslt.getString("nm_pekerjaan");
                String[] data = {id, pekerjaan};
                tableModel.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormMasterPekerjaan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void update_data() {
        //panggil method koneksi seperti biasa
        java.sql.Connection conn = new DBConnection().connect();
        
        String sql = "Update pekerjaan set nm_pekerjaan=? "
                + "where id_pekerjaan = '"+txt_id.getText()+"'";
        java.sql.PreparedStatement stmt = null;
        
        try {
            stmt = conn.prepareStatement(sql);
            
            stmt.setString(1, txt_nama.getText());
            
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
            
            tampil_data();
            
        } catch (SQLException ex) {
            Logger.getLogger(FormMasterPekerjaan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void hapus_data() {
        //panggil method koneksi terlebih dahulu
        java.sql.Connection conn = new DBConnection().connect();
        
        int yes = JOptionPane.showConfirmDialog(FormMasterPekerjaan.this, 
                "Apakah anda yakin?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (yes==0) {
            try {
                String sql = "delete from pekerjaan where id_pekerjaan = '"+txt_id.getText()+"'";
                java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
                
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(FormMasterPekerjaan.this, "Data Berhasil dihapus.");
                //untuk mengosongkan data setelah dihapus
                txt_id.setText("");
                txt_nama.setText("");
                
                tampil_data();
            } catch (SQLException ex) {
                Logger.getLogger(FormMasterPekerjaan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(FormMasterPekerjaan.this, "Data gagal dihapus.");
            }
        }
    }

    private void klik_tabel() {
        int baris = tabel_pekerjaan.getSelectedRow();
        String idx = tableModel.getValueAt(baris, 0).toString();
        String namax= tableModel.getValueAt(baris, 1).toString();
        
        txt_id.setText(idx);
        txt_nama.setText(namax);
    }
}
